### ISSUE TITLE
Visual Studio 2015 Support

### ISSUE THREAD

**Issue by bartsipes** [DanTup/TestAdapters#37]
Please add support for VS 2015.

**Comment by mario-galindo** [comment]
I agree with that, please add support to Visual Studio 2015

**Comment by CullenShane** [comment]
While you're at it, 2017 support would be nice....

5/1/2017 1:35:10 PM - Microsoft VSIX Installer
5/1/2017 1:35:10 PM - -------------------------------------------
5/1/2017 1:35:10 PM - vsixinstaller.exe version:
5/1/2017 1:35:10 PM - 15.0.26403.7 built by: D15SVC
5/1/2017 1:35:10 PM - -------------------------------------------
5/1/2017 1:35:10 PM - Command line parameters:
5/1/2017 1:35:10 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\North Park Innovatio\Downloads\DanTup.TestAdapters.Karma.Vsix.vsix
5/1/2017 1:35:10 PM - -------------------------------------------
5/1/2017 1:35:10 PM - Microsoft VSIX Installer
5/1/2017 1:35:10 PM - -------------------------------------------
5/1/2017 1:35:10 PM - Initializing Install...
5/1/2017 1:35:11 PM - Extension Details...
5/1/2017 1:35:11 PM - 	Identifier         : 908a18f2-e3a1-4300-982e-bb46baa7b181
5/1/2017 1:35:11 PM - 	Name               : VS Adapter for Google's Karma Test Runner
5/1/2017 1:35:11 PM - 	Author             : Danny Tuppeny
5/1/2017 1:35:11 PM - 	Version            : 1.10
5/1/2017 1:35:11 PM - 	Description        : Test Adapter to integration test results from Google's Karma Test Runner into Visual Studio.
5/1/2017 1:35:11 PM - 	Locale             : en-US
5/1/2017 1:35:11 PM - 	MoreInfoURL        : https://github.com/DanTup/TestAdapters/blob/master/README.karma.md
5/1/2017 1:35:11 PM - 	InstalledByMSI     : False
5/1/2017 1:35:11 PM - 	SupportedFrameworkVersionRange : [4.5,)
5/1/2017 1:35:11 PM - 
5/1/2017 1:35:11 PM - 	SignatureState     : Unsigned
5/1/2017 1:35:11 PM - 	Supported Products : 
5/1/2017 1:35:11 PM - 		Microsoft.VisualStudio.Pro
5/1/2017 1:35:11 PM - 			Version : [12.0]
5/1/2017 1:35:11 PM - 
5/1/2017 1:35:11 PM - 	References         : 
5/1/2017 1:35:11 PM - Signature Details...
5/1/2017 1:35:11 PM - 	Extension is not signed.
5/1/2017 1:35:11 PM - 
5/1/2017 1:35:11 PM - Searching for applicable products...
5/1/2017 1:35:11 PM - Found installed product - Global Location
5/1/2017 1:35:11 PM - Found installed product - Visual Studio Community 2017
5/1/2017 1:35:11 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
